### ISSUE TITLE
Random disconnects - Kicked for trying to create an existing subspace

### ISSUE THREAD

**Issue by Nahaz** [godarklight/DarkMultiPlayer#284] opened 2015-01-03 18:46 UTC
I'm getting randomly disconnected, I'm not doing much more than being in VAB or launching/flying a rocket.

This is from the server console:
![dmp-disconnect](https://cloud.githubusercontent.com/assets/457154/5603342/fd0cda76-9380-11e4-8c2c-da5cbff1eab7.PNG)

I've tried having 2 different clients on my own comp when playing with friends and it's only the one I'm actually plaing in that disconnects (I have the other one idle in tracking station)

**Comment by oldmud0** [comment] 2015-01-03 22:33
I've seen other players complain about this same problem on servers.

**Comment by RockyTV** [comment] 2015-01-04 01:47
Something I'd like to take a look at.

**Comment by andremiller** [comment] 2015-01-07 18:19
We just got the same error, for us it happened in Career mode, when one player clicked the Revert to Launch button.

At the time I was actually about to launch my own craft, in the safety bubble.

[19:37:14][DEBUG] : Kicked for trying to create an existing subspace
[19:37:14][INFO] : Disconnecting client xxxx, sent CONNECTION_END (Kicked for trying to create an existing subspace) to endpoint xxxx
[19:37:14][DEBUG] : Online players is now: 1, connected: 1

**Comment by godarklight** [comment] 2015-01-07 18:23
RockyTV: This one is actually an easy one, here's the cause:
https://github.com/godarklight/DarkMultiPlayer/blob/master/Server/Messages/WarpControl.cs#L52-L57

This is a direct result of the warp system being far too peer-to-peer than it should be, The fix would be to rip out the created subspace ID out of the message, and build a new subspace from the new details, and then sending the client coming out of warp into that subspace via WARP_CONTROL/SET_SUBSPACE.

This is pre v0.1.0.0 lazyness :P

**Comment by RockyTV** [comment] 2015-01-07 20:46
@godarklight Maybe call SendSetSubspace()?

**Comment by godarklight** [comment] 2015-01-24 01:52
This issue is addressed in the warp-rework branch - I'll close this when it hits dev.

**Closed** 2015-02-28 17:45 UTC
