### ISSUE TITLE
Synced Science/Career Mode

### ISSUE THREAD

**Issue by bananashavings** [godarklight/DarkMultiPlayer#353] opened 2015-12-06 19:01 UTC
Hey, Im wondering if theres a way to have a synced career or science mode. I think for private servers with your friends if could be extremely fun, and If its not implemented already, I definitely think it should be. Thanks!

**Comment by RockyTV** [comment] 2015-12-06 20:12
Closing this issue because it is a duplicate of #72. Track it there instead.

**Closed by RockyTV** 2015-12-06 20:12 UTC
