### ISSUE TITLE
Clients are out of sync

### ISSUE THREAD

**Issue by Ricktza** [godarklight/DarkMultiPlayer#286] opened 2015-01-07 00:24 UTC
Sometimes clients can become out of sync over time, to get back in sync the one behind has to warp to get the sync button to display to re sync with the server.
Seems to happen mostly when near by another player.

**Comment by godarklight** [comment] 2015-01-07 18:35
If this was in low-level career mode while in flight, it's fixed in v0.2.0.2 ;)

**Comment by Ricktza** [comment] 2015-01-07 19:28
We are in sandbox, let me explain a little better :)

I'm currently running 0.2.02 on linux using mono

What i have noticed is players can be between <1-6 seconds out of sync sometimes longer while both players are sync'd.
The one that is delayed has to press > then  < quickly to then get the sync button back.

Also if players are out of sync by lets say 3 seconds you will gradually see that increase to 5 or so.

I have a feeling that it may be caused by the player lagging either by fps/connection causing it to desync while sync to the latest subspace.

However the server was originally started in career mode on 0.2.0.0 which was very buggy and out of sync which i noticed you patched so i updated. (clients was also all updated.)

I noticed in the connection statistics it can take between 100ms - 5000ms for data to be sent or received.
I don't know if this is normal but i have a feeling it's also part of what is causing everything to desync over time. 

The server is run on a VPS which isn't lagging and has a decent connection.

**Comment by godarklight** [comment] 2015-02-28 17:45
Likely caused by the process new messages throw ;)

**Closed by godarklight** 2015-02-28 17:45 UTC
